### PR TITLE
Syntax Errors 

### PR DESCRIPTION
**Pull request by arshidkv12**
Please check syntax errors.

### CODE REVIEW

**Comment by timint** [comment]
Oh heck no!



Don't make pull requests if you don't know what you are doing.

**Comment by arshidkv12** [comment]
> Oh heck no!
> 
> 
> 
> Don't make pull requests if you don't know what you are doing.

Sorry... It was version issue.

**Comment by arshidkv12** [comment]
Please check other files.

**Comment by timint** [comment]
Thanks, I got it. See referenced commits.

**Pull request closed without merging**
