### PR TITLE
Syntax Error

### PR DESCRIPTION
**Pull request by arshidkv12**
Please check 5354117

### CODE REVIEW

**Comment by timint** [comment]
Same as previous faulty pull request. The only new is your commit to lib_route.inc.php.
https://github.com/litecart/litecart/pull/238/commits/7be2fcf36728ec2d46d256b3cce9aff17bb78016

**Comment by arshidkv12** [comment]
new email() not defined.

**Comment by arshidkv12** [comment]
It is an automatic pull request. You can merge, what you are okay with it.

**Comment by arshidkv12** [comment]
Please merge like https://github.com/opencart/opencart/commits?author=arshidkv12

**Comment by timint** [comment]
Could you make some more sense please?

**Pull request closed without merging**
