### PR TITLE
Update autoloader.inc.php

### PR DESCRIPTION
**Pull request by arshidkv12**

### CODE REVIEW

**Comment by timint** [comment]
Thanks, I need to give this thinking. So I am closing this meantime. I would have wanted change the syntax anyway.

**Comment by arshidkv12** [comment]
It needed to load composer library.

**Comment by timint** [comment]
Right, so put composer in ~/vendor/composer/ and the autoloader in ~/vendor/autoload.php and LiteCart should autodetect it.

**Comment by arshidkv12** [comment]
I think, it will make conflict with different modules.

**Comment by timint** [comment]
Should not be a problem. As the Composer autoloader uses prepend for spl_register_autoload().

**Pull request closed without merging**
