### PR TITLE
Avoid autoload error (composer issue)

### PR DESCRIPTION
**Pull request by arshidkv12**

### CODE REVIEW

**Comment by timint** [comment]
Composer should prepend the spl_autoload_register(). Does it not?

See prepend:
https://www.php.net/spl_autoload_register

**Comment by arshidkv12** [comment]
It is making trouble, if we create addon with composer. So I added
file_exists function to avoid this problem.

**Comment by timint** [comment]
Is it so that Composer prepend autoload is set to true but the composer package it tries to access is missing? There are several ways to solve this. And I wanna be sure this is it.

**Comment by arshidkv12** [comment]
I added stripe library with composer in module folder. Then I included
autoload.php in my module. Then it is making error.

**Comment by timint** [comment]
What happens if you remove your autoloader and just rely on this?
https://github.com/litecart/litecart/blob/dev/public_html/includes/app_header.inc.php#L26

**Comment by arshidkv12** [comment]
Not loading vendor autoload file inside module directory (eg: payment)

**Comment by timint** [comment]
And your vendor autoload file is ~/vendors/autoload.php?
And you say it's Composer.

It makes no sense. Composer should always prepend the autoloader as included in includes/app_header.inc.php.

**Comment by arshidkv12** [comment]
I separately downloaded stripe files by composer. My vendor folder is
inside include/module/payment/stripe/vendor.

**Comment by timint** [comment]
See if this is a better solution
https://www.litecart.net/en/addons/255/composer-for-litecart

**Comment by arshidkv12** [comment]
Please note, I am developing addon.

**Comment by arshidkv12** [comment]
Please check responsive issue also  https://prnt.sc/rp9pkd

**Comment by timint** [comment]
Closing as conflicting code and seems to be a few versions behind.

**Comment by arshidkv12** [comment]
Cloned from dev branch.

**Pull request closed without merging**
